SELECT TB.ORDERID, TB.TITLE ,TB.NAME ,TB.SURNAME,TB.ADDRESS, TB.ZIPCOD ,NULL AS CATEGORYID ,TB.CATEGORYNAME ,TB.VATRATE, TB.PORTFEE, TB.QTYPORT ,
	TB.TOTALFEEAMOUNT ,TB.PORTFEE ,TB.ADDRESS1 , TB.ADDRESS2 , TB.ADDRESS3 ,NULL AS BRANCHNAME ,TB.BRANCH_NO AS BRANCHCODE,
	TB.TAXID,TNO.SERVICENO AS MDN ,TNO.ICCID AS ICCD,TB.PORTFEE AS TOTALAMOUNT ,TB.REF AS ORDERID_REF
	FROM TBMNPMASORDER TB 
	RIGHT JOIN TBMNPMASSERVICENO TNO ON TB.ORDERID = TNO.ORDERID  WHERE TB.ORDERID =:orderId AND TB.FLAG ='A' AND TNO.FLAG='A';