
UPDATE TBMNPTRSRECEIPT
	SET 
		BILLINGACC = NVL(:accountNo,BILLINGACC),
		ACCOUNTNAME = NVL(:accountName,ACCOUNTNAME),
		OFFICERNAME = NVL(:officerName,OFFICERNAME),
		CANCELREASON = NVL(:cancelReason,CANCELREASON),
		CANCELDATE = NVL(:cancelDate,CANCELDATE) ,
		SERVICENO = NVL(:serviceNo,SERVICENO),
		BRANCH_NO = NVL(:branch,BRANCH_NO)
		
	WHERE RECEIPTID = :receiptId ;
	--AND SERVICENO = :serviceNo
	UPDATE TBMNPTRSRECEIPTDETAIL
	SET
		CANCELDATE = NVL(:cancelDate,CANCELDATE), 
		CANCELREASON = NVL(:cancelReason,CANCELREASON) , 
		CANCELREASONID = NVL(:cancelReasonId,CANCELREASON) , 
		CANCELNOTE = NVL(:cancelNote,CANCELNOTE) ,
		SERVICENO = NVL(:serviceNo,SERVICENO),
		CANCELAPPROVE = NVL(:cancelApprove,CANCELAPPROVE)
		
	WHERE RECEIPTID = :receiptId;
	
	UPDATE TBMNPMASORDER
	SET
		FLAG ='A'
	WHERE ORDERID = :orderId;
	
	UPDATE TBMNPMASSERVICENO
	SET
		ISACTIVE ='A',
		FLAG ='A'
	WHERE ORDERID = :orderId;
		